### register user
POST http://localhost:5000/api/user/register
Content-Type: application/json

{
  "fullName": "newuser",
  "email": "newuser7@example.com",
  "password": "securepassword"
}

### login user
POST http://localhost:5000/api/user/login  
Content-Type: application/json

{
  "email": "memonyasin2007@gmail.com",
  "password": "YasinMemon@10"
}

### register doctor
POST http://localhost:5000/api/doctor/register
Content-Type: application/json

{
  "fullName": "Dr. John Doe",
  "email": "memonyasin3007@gmail.com",
  "phone": "+1234567890",
  "password": "securepassword", 
  "specialty": "Cardiology",
  "experience": 10,
  "qualifications": ["MD"],
  "registration_number": "REG123456",
  "hospital_name": "HealthCare Hospital",
  "city": "Health City",
  "consulation_type": "Online",
  "consulation_fee": 150,
  "available_days": ["Monday", "Wednesday", "Friday"],
  "time_slots": ["10:00-12:00", "14:00-16:00"],
  "conclusion_duration": 30,
  "medical_license": "something.pdf",
  "goverment_id": "idproof.pdf"
}

### login doctor
POST http://localhost:5000/api/doctor/login
Content-Type: application/json

{
  "email": "zakirshaikh23@gmail.com",
  "password": "Yasin@10"
}

### doctor logout
POST http://localhost:5000/api/doctor/logout
Content-Type: application/json

{
  "token": "<doctor_jwt_token>"
} 

### delete and create admin
GET http://localhost:5000/api/admin/create

### admin login
POST http://localhost:5000/api/admin/login
Content-Type: application/json

{
  "username" : "doctor",
  "password" : "password"
}

### get all doctors (admin only)
GET http://localhost:5000/api/admin/doctors
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImRvY3RvciIsInJvbGUiOiJhZG1pbiIsImlhdCI6MTc3MDIwMTg0NSwiZXhwIjoxNzcwMjg4MjQ1fQ.ED0jfheo-qaJJ5s32KINBb1-kVPpw0ZdG1CKo63JeX8

### get Doctor by Specialization
GET http://localhost:5000/api/user/verified/doctors/Cardiologist


### create appointment
POST http://localhost:5000/api/appointment/create
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5N2VkMTliNjFmMDMwNDgwOGJiOWIyOCIsImlhdCI6MTc3MDI2OTA5NCwiZXhwIjoxNzcwMzU1NDk0fQ.YcaSIo9_kO0zh_ZNXk4cUZvnczYqHEwU2cf2IhMYGfA

{
  "doctorId": "6983274f4fb97e73742c0da4",
  "appointmentDate": "2026-02-09",
  "timeSlot": ["2"],
  "consultationType": "Online"
}

### get doctor appointments
GET http://localhost:5000/api/doctor/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5ODMzMzI2MGI3NzBhNmRlOWIxYWI1ZCIsImlhdCI6MTc3MDg3MjQ1MCwiZXhwIjoxNzcwODc2MDUwfQ.z3yVE3WD9fKczUl8w8-uNIFOynIsCvENCLmph3T_i2Q

### get user appointments
GET http://localhost:5000/api/user/appointments
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5N2VkMTliNjFmMDMwNDgwOGJiOWIyOCIsImlhdCI6MTc3MTIxNzQyMywiZXhwIjoxNzcxMzAzODIzfQ.WkkdOLpiswjK35hidfQ1xhcA3sg_5CuCNiW15Nz_1Co

### update doctor schedule
PUT http://localhost:5000/api/doctor/schedule
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5OTJiMjk3ZDg2YTgwY2I0NGI2NjgwMSIsImlhdCI6MTc3MTIzODM4MiwiZXhwIjoxNzcxMzI0NzgyfQ.J52Upi2o-0RQWqCcc71-UuLr_qX5rN6vxefu1QhuJbQ

{
  "available_days": ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday"],
  "time_slots": ["10:00-12:00", "14:00-16:00"]
}

### get doctor availability
GET http://localhost:5000/api/doctor/availability
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6IjY5YmEyZmU4N2UxYTc2NzBiMzViZWMwNyIsInJvbGUiOiJkb2N0b3IiLCJpYXQiOjE3NzM4MTA4ODAsImV4cCI6MTc3Mzg5NzI4MH0.vhAFViIx0NA_eYJH5RYIr9PQuRtxs4u7rpWQ4eeQO5k

###